# Generated by Django 4.1 on 2022-09-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_facebook_url_profile_instagram_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_url',
            new_name='facebook_page',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instagram_url',
            new_name='instagram_page',
        ),
    ]
