# Generated by Django 4.1 on 2022-08-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_car_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='year',
            new_name='color',
        ),
        migrations.AddField(
            model_name='car',
            name='date_of_production',
            field=models.CharField(default='', max_length=50),
        ),
    ]
