# Generated by Django 4.1 on 2022-08-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_rename_year_car_color_car_date_of_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='no_image.png', upload_to='users_cars_pics'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Petrol/LPG', 'Petrol/LPG'), ('Hybrid', 'Hybrid'), ('Electrical', 'Electrical')], max_length=50),
        ),
    ]
