# Generated by Django 4.1 on 2022-08-28 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_alter_car_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 14, 17, 23, 139269)),
        ),
    ]
