# Generated by Django 4.1 on 2022-08-28 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_car_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 19, 41, 30, 452222)),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Petrol / LPG', 'Petrol / LPG'), ('Hybrid', 'Hybrid'), ('Electrical', 'Electrical')], max_length=50),
        ),
    ]
