# Generated by Django 4.1 on 2022-08-28 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_alter_car_created_alter_car_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 22, 52, 29, 782372)),
        ),
    ]
