# Generated by Django 4.1 on 2022-09-18 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0011_alter_car_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 19, 24, 51, 766680)),
        ),
    ]
