# Generated by Django 4.1 on 2022-09-18 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0012_alter_car_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 19, 47, 23, 654435)),
        ),
    ]
